openapi: 3.0.0
info:
  title: Food Delivery API
  version: 1.0.0
  description: >
    This API calculates delivery costs for different types of food items across various zones based on the distance and item type.
servers:
  - url: http://localhost:8000
paths:
  /pricing/calculate-price:
    post:
      summary: Calculate delivery price
      description: Calculate the total cost of food delivery based on various factors.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                organization_id:
                  type: string
                total_distance:
                  type: number
                item_type:
                  type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
        "400":
          description: Bad request
        "404":
          description: Pricing not found for the given parameters
        "500":
          description: An error occurred while processing the request
  /calculate-price:
    post:
      summary: Calculate delivery price
      description: Calculates the total cost of food delivery based on zone, distance, and item type.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                  description: Delivery zone
                  example: "central"
                organization_id:
                  type: string
                  description: Organization ID
                  example: "005"
                total_distance:
                  type: number
                  description: Total distance in kilometers
                  example: 12
                item_type:
                  type: string
                  description: Type of item (perishable or non-perishable)
                  example: "perishable"
      responses:
        "200":
          description: Successful price calculation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
                    description: Total delivery price in cents
                    example: 2050
